[package]
name = "rust"
version = "0.1.0"
authors = ["flauntingspade4 <48335751+flauntingspade4@users.noreply.github.com>"]
edition = "2018"

[profile.release]
lto = 'thin'
panic = 'abort'
codegen-units = 1

#[lib]
#name = "rust"
#crate-type = ["cdylib"]

[dependencies]
plotters = "^0.3.0"